name: Android CI

on:
  push:
    branches: 
      - main
      - master
    paths-ignore:
      - 'source/**'
      - '**.md'
      - '.**'
      - 'fastlane/**'
  pull_request:
    paths-ignore:
      - 'source/**'
      - '**.md'
      - '.**'
      - 'fastlane/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NDK_VERSION: 29.0.14206865

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Install NDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;${{ env.NDK_VERSION }}"

      - name: Install Cargo with aarch64-linux-android
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Add Rust target architectures
        run: |
          rustup target add x86_64-linux-android
          rustup target add armv7-linux-androideabi

      - name: Retrieve version
        run: |
          echo VERSION=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - name: Build with Gradle (debug)
        run: ./gradlew -PappVerName=${{ env.VERSION }} assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          path: './app/build/outputs/apk/debug/*.apk'
          name: build_debug_${{ env.VERSION }}
